src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
    const HEAT = [
        0 => 'electric',
        1 => 'gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getSlugify(): ?string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): ?string
    {
        return number_format($this->price,0,'',' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): ?string
    {
        return self::HEAT[$this->heat] ? self::HEAT[$this->heat] : null;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
//            pour la traduction, on ajoute de préférence 'traslation_domain' dans configureOptions
//            ->add('title', null, ['label' => 'Titre'])
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
//            ->add('created_at', DateType::class, [
//                'widget' => 'single_text',
//                // this is actually the default format for single_text
//                'format' => 'yyyy-MM-dd',
//            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        return array_flip(Property::HEAT);
    }
}

src/Controller/PropertyController.php
<?php
/**
 * Created by PhpStorm.
 * User: nesrine
 * Date: 25/03/19
 * Time: 18:06
 */

namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class PropertyController extends AbstractController
{
    /**
     * @param PropertyRepository $propertyRepository
     * @return Response
     */
    public function index(PropertyRepository $propertyRepository) : Response
    {
//        $repository = $this->getDoctrine()->getRepository(Property::class); // on peut aussi utiliser ça et dans ce cas pas besoin d'ajouter PropertyRepository en paramètre
        $biens = $propertyRepository->findAllVisible();

        return $this->render("property\index.html.twig", [
            'current_menu' => 'properties',
            'biens' => $biens
        ]);
    }

    /**
     * @param int $id
     * @param string $slug
     * @param PropertyRepository $propertyRepository
     * @return Response
     */
    public function showProperty($id, $slug, PropertyRepository $propertyRepository) : Response
    {
        $property = $propertyRepository->find($id);
        switch ($property):
            case null:
                return $this->redirectToRoute('home');
            default:
                if($slug !== $property->getSlugify()) {
                    return $this->redirectToRoute('property.show', ['id' => $property->getId(), 'slug' => $property->getSlugify()]);
                }

                return $this->render("property\property.html.twig", [
                    'current_menu' => 'properties',
                    'property' => $property
                ]);
        endswitch;
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens' %}
{% block body %}
    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>

    {% if biens is defined %}
        {% for bien in biens %}
            {{ bien.getTitle() }} <br>
        {% endfor %}
    {% endif %}
    </div>
{% endblock %}

templates/property/property.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}
{% block body %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
            </div>
            <div class="col-md-4">
                <h1>{{ property.title }}</h1>
                <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>
                <p>{{ property.description | nl2br }}</p>
                <div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.price }} €</div>
                <a class="btn btn-primary" href="#"> Contacter l'agence </a>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques du bien</h2>
                <table class="table table stripped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m2</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etages</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    {% if property.heatType is defined %}
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                    {% endif %}
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>
{% endblock %}